src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/forms/aims/model/AimsReferral.java, src/main/java/ca/bc/gov/chefs/etl/forms/aims/model/MainEntity.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/facility/json/Root.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/facility/model/FacilityInformation.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/facility/processor/FacilityInfoFormApiResponseProcessor.java
Updated ETL process for AIMS form following the new data model
=> ETL process update for AIMS form 

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/json/Root.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/model/LtcYtdCompAddPos.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/processor/LtcQuarterlyYtdApiResponseProcessor.java
Includes many bugfixes.
Complete remapping of existing labels, replacing magic strings
=> Big fix for LTC_YTD ETL process, complete remapping of existing labels

src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/util/FileUtil.java, src/main/resources/application-dev.properties
moved password definition to properties file. Modifying mock password to be "tbd"
=> Hiding Mock password

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/facility/model/FacilityInformation.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/model/LtcBedYtdMaxOccupancy.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/model/LtcYtdSubmission.java
bugfix, we no longer format to date if string is blank or empty
=> Date formatting bugfix

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/json/Root.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/processor/LtcQuarterlyYtdApiResponseProcessor.java
Complete remapping following the new form Version
=> Ltc ytd revisited

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/staffing/processor/LTCStaffingPlanApiResponseProcessor.java
incrementing the string with the corresponding index
=> Staffing Plan : forcing otherName to be unique for LTCStaffPlanPosType

src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/util/FileUtil.java, src/main/resources/application-dev.properties
- Added "guid.suffix" flag to constants and application properties.
- Added parsing and checking for the flag value.
- Added GUID concatenation based on flag value.
=> BCMOHAD-18055: Setup unique GUID suffixes to all extracted files

src/main/java/ca/bc/gov/chefs/etl/core/routes/BaseRoute.java
- Added stack dump and error cause on BaseRoute
=> BCMOHAD-18055: Added extra error logging and stack trace

src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/core/model/FileProperties.java, src/main/java/ca/bc/gov/chefs/etl/core/routes/BaseRoute.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/budget/route/LtcAnnualBudgetRoute.java, src/main/java/ca/bc/gov/chefs/etl/util/FileUtil.java, src/main/resources/application-dev.properties
- Added a feature flag that would allow for LTC and PCD files to go into their respective directories.
- Added a checker and loggings on the encryptAllFiles function to append the directories to the generated files by checking the file's path for "ltc" or "pcd".
=> BCMOHAD-23159: PCD BI - ETL Code Change - New Encrypted directories for LTC and PCD Encrypted Files

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/processor/LtcQuarterlyYtdApiResponseProcessor.java
- Added a function to handle values that are throwing errors on HealthIdeas, this is done by adding a custom validation on the setSubTotalRevYtd() function.
=> 11056: Fixes for version 17 bug in string concatenation

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/processor/LtcQuarterlyYtdApiResponseProcessor.java
- Added logic to handle the total and subtotal calculations on ETL side.
=> 11056: Added logic to handle totals and subtotals affected by version 17 of YTD

src/main/java/ca/bc/gov/chefs/etl/forms/pcd/practitionerRoleMapping/json/Root.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/practitionerRoleMapping/processor/PcdPractitionerRoleMappingApiResponseProcessor.java
Property names didn't match json so mappings weren't being picked up/exported.
=> Fix Prac Role Mapping

src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/staffing/processor/LTCStaffingPlanApiResponseProcessor.java
- Constants for HCA, LPN, Days, Nights and Evenings.
- Replaced repeating labels with constants.
=> Fixing HI failed load for 2025-01-09

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/staffing/processor/LTCStaffingPlanApiResponseProcessor.java
- Replacing the wrong values from CHEFS with constants from LTC_STAFFING_ADD_POS
=> LTC Data Load Remediation for 1-13-2025

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/budget/model/LtcBudgetSubmission.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/model/LtcYtdSubmission.java
- Added default value for new fields to pass HI required checks.
=> HI Load remediation for 1-14-2025

docker/Dockerfile, src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/staffing/model/LTCStaffingPlan.java
- Adding "NaN" handlers for LTC_STAFFING_PLAN CUMULATIVE_TOTAL_DCH columns Q1-Q4.
=> HI Data Load Remediation for 1-15-2025

doc/DomainModelDomains.txt
- Added 2 missing DOMAINS for the POSITION_NAME.
=> Adding missing DOMAINS for POSITION_NAME

src/main/java/ca/bc/gov/chefs/etl/forms/pcd/chc/pcPatientServices/processor/PcdChcPCPSApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/hrRecords/processor/PcdHRRecordsApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/provincialRiskTracking/model/ProvincialRiskTracking.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/provincialRiskTracking/processor/ProvincialRiskTrackingApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/statusTracker/model/IssueAndRisk.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/statusTracker/processor/StatusTrackerFormApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/upcc/financialReporting/processor/PcdUpccFRApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/upcc/pcPatientServices/processor/PcdUpccPCPSApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/util/JsonUtil.java
Fixes as a result of acceptance testing on most recently delivered ETLs.
=> BCMOHAD-27375 - UAT fixes

src/main/java/ca/bc/gov/chefs/etl/forms/ltc/budget/processor/LtcAnnualBudgetApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/facility/processor/FacilityInfoFormApiProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/facility/processor/FacilityInfoFormApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/quarterly/processor/LtcQuarterlyYtdApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/staffing/processor/LTCStaffingPlanApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/ltc/staffing/processor/LtcStaffingPlanApiProcessor.java
Added fix for ASCII characters.
Added null safety for missing property.
Code cleanup.
=> Fix non-ASCII issues found in UAT testing

src/main/java/ca/bc/gov/chefs/etl/forms/pcd/chc/pcPatientServices/processor/PcdChcPCPSApiProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/chc/pcPatientServices/processor/PcdChcPCPSApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/chc/pcPatientServices/route/ChcPcpsFormRoute.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/haMapping/aggregation/HaMappingAggregationStrategy.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/upcc/pcPatientServices/processor/PcdUpccPCPSApiProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/upcc/pcPatientServices/processor/PcdUpccPCPSApiResponseProcessor.java, src/main/java/ca/bc/gov/chefs/etl/forms/pcd/upcc/pcPatientServices/route/UpccPcpsFormRoute.java
Add HA Mapping to CHC and UPCC.
Update HA Mapping generation to remove non-ASCII characters for matching with submission data.
=> BCMOHAD-27308 - Patient services HA Mapping

openshift/app.cm.yaml, src/main/java/ca/bc/gov/chefs/etl/constant/Constants.java, src/main/java/ca/bc/gov/chefs/etl/util/FileUtil.java, src/main/resources/application-dev.properties
Added support for a custom PGP key and folder for ODS.
=> Changes for ODS
